name = "albyyyy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"
author = "zkulb"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e0aa4e973d532b1b527bca9f94d126c04cdffc0de2788f659dea6c4004ca1f1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
