name = "albyyyy"
author = "zkulb"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fa00926ac08c52107ec568059ace9f2ec9dda537bed362236ddaa90aa0a43d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
